modLoader="javafml"
loaderVersion="[36,)"
license="LGPL 2.1"
[[mods]] #mandatory
modId="twilightdecor" #mandatory
version="1.1" #mandatory
displayName="Twilight Decor" #mandatory
logoFile="twilightdecor.png" #optional
authors="jodlodi" #optional
description='''
A small mod which aims to give compatibility for decoration mods to the Twilight Forest mod.
'''
[[dependencies.twilightdecor]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.twilightdecor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.twilightdecor]]
    modId="blueprint"
    mandatory=true
    versionRange=",)"
    ordering="NONE"
    side="BOTH"

[[dependencies.twilightdecor]]
    modId="twilightforest"
    mandatory=true
    versionRange=",)"
    ordering="NONE"
    side="BOTH"

[[dependencies.twilightdecor]]
    modId="decorative_blocks"
    mandatory=true
    versionRange=",)"
    ordering="NONE"
    side="BOTH"